ALTER TYPE "BookingStatus" ADD VALUE 'DECLINED';

ALTER TABLE "Booking"
ADD COLUMN "requestMessage" TEXT,
ADD COLUMN "landownerResponse" TEXT,
ADD COLUMN "requestedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "respondedAt" TIMESTAMP(3);
